server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalogo-service
          uri: lb://catalogo-service
          predicates:
            - Path=/api/service/catalogo/**
          filters:
            - AuthFilter
        - id: inventario-service
          uri: lb://inventario-service
          predicates:
            - Path=/api/service/inventario/**
        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/venta/**
        - id: archivo-service
          uri: lb://archivo-service
          predicates:
            - Path=/archivo/**
        - id: reporte-service
          uri: lb://reporte-service
          predicates:
            - Path=/reporte/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
     